name: Deploy Auth to NuGet

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

# https://tehgm.net/blog/nuget-github-actions/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v2
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: "6.0"
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}

      - name: Install dependencies
        run: dotnet restore

      - name: Publish Auth
        run: |
          mkdir __out
          dotnet pack BattlelineUtilities.AspNetCore.Auth -c Release -o __out --no-restore
          dotnet nuget push "./__out/*.nupkg" --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_TOKEN}}
          rm -rf __out
