name: Deploy Auth to NuGet

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v2
        with:
          source-url: https://api.nuget.org/v3/index.json
          dotnet-version: "6.0"
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
      - name: Build Project
        run: |
          dotnet build BattlelineUtilities.AspNetCore.Auth --configuration Release
      - name: Build solution and generate NuGet package
        run: |
          cd BattlelineUtilities.AspNetCore
          dotnet pack -c Release -o out
      - name: Push generated package to NuGet registry
        run: dotnet nuget push ./BattlelineUtilities.AspNetCore.Auth/out/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate --no-symbols true
